apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: r-redis
  namespace: knative-samples
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/philipz/r-redis