# helloworld-python app deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cud-redis
  namespace: knative-samples
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: cud-redis
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: cud-redis
          image: docker.io/philipz/cud-redis
          imagePullPolicy: Always
---
# Service that exposes helloworld-python app.
# This will be the subscriber for the Trigger
apiVersion: v1
kind: Service
metadata:
  name: cud-redis
  namespace: knative-samples
spec:
  selector:
    app: cud-redis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
# Knative Eventing Trigger to trigger the helloworld-python service
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: cud-redis
  namespace: knative-samples
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.helloworld
      source: dev.knative.samples/helloworldsource
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: cud-redis
